# Generated by Django 5.1.7 on 2025-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tire1_class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("teaher", models.CharField(max_length=16)),
                ("term", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="tire2_class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("teaher", models.CharField(max_length=16)),
                ("term", models.IntegerField()),
            ],
        ),
    ]
