# Generated by Django 5.1.7 on 2025-03-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire1_class",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="tire1_class",
            name="teaher",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="tire1_class",
            name="term",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="tire2_class",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="tire2_class",
            name="teaher",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="tire2_class",
            name="term",
            field=models.CharField(max_length=64),
        ),
    ]
